### ISSUE TITLE
item_tax_rate_percent outputs currency sign instead of percent

### ISSUE THREAD

**Issue by klodeckl** [InvoicePlane/InvoicePlane#1002]
In the pdf template the function $item->item_tax_rate_percent)); outputs a euro sign instead of the percentage sign (e.g. 19 € instead of 19 %).

Invoiceplane 1.5.11
PHP 7.4

**Comment by nielsdrost7** [comment]
Thank you for your issue.
The latest version of InvoicePlane is version 1.6.1

Please fill the template with as much information as possible (steps to reproduce):



## Expected Behavior


## Current Behavior


## Screenshots


## Possible Solution


## Steps to Reproduce


1.
2.
3.
4.

## Context (Environment)





## Detailed Description


## Possible Implementation


## Failure Logs

**Comment by nielsdrost7** [comment]
@klodeckl were you able to find that extra requested information?
I'll close the issue for now
