### ISSUE TITLE
discount product can be good calculation , here fix

### ISSUE THREAD

**Issue by reproteq** [InvoicePlane/InvoicePlane#1016]
https://pastebin.com/HrW9wsaB

**Comment by nielsdrost7** [comment]
@reproteq thank you for your improvement regarding discount calculation.
I'm looking for thr reason that you made this improvement.

Could you help by filling (part) of below questions.
Especially the `Steps to Reproduce` and the `Context` will help with **why** you made this improvement

## Expected Behavior


## Current Behavior


## Screenshots


## Possible Solution


## Steps to Reproduce


1.
2.
3.
4.

## Context (Environment)





## Detailed Description


## Possible Implementation


## Failure Logs

**Comment by reproteq** [comment]
uso este software para hacer mis facturas y me di cuenta que si aplico un
descuento las tasas se calculan mal , porque la tasa se tiene que calcular
de lo que va a pagar el cliente , con estos cambios he conseguido que
calcule correctamente las tasas respecto al descuento.
simplemente me funciona bien así y así es como lo estoy haciendo en mi
invoiceplane.
Reproteq®
Electrónica y reprogramación.

**Comment by reproteq** [comment]
[image: image.png]
Reproteq®
Electrónica y reprogramación.

**Comment by nielsdrost7** [comment]
I've translated it for you to the English language:

> I use this software to make my invoices and I realized that if I apply a
> discount rates are calculated incorrectly, because the rate has to be calculated
> of what the client is going to pay, with these changes I have managed to
> correctly calculate the rates with respect to the discount.
> It just works well for me like this and that's how I'm doing it on my
> invoiceplane.

**Comment by nielsdrost7** [comment]
@reproteq 
Regarding this sentence:

> if I apply a
discount rates are calculated incorrectly, because the rate has to be calculated
of what the client is going to pay

Do you have a nice example? That helps to reproduce the problem, right before we implement your solution

**Comment by nielsdrost7** [comment]
No examples, no responses, closing the issue
