### ISSUE TITLE
Broken link when deleting client

### ISSUE THREAD

**Issue by juansecaro** [InvoicePlane/InvoicePlane#1041]
An error appear when trying to (soft) delete a client with notes.
Version 1.6.1
PHP 8.1
MySQL 8.0

## Steps to Reproduce

1.
2.
3.
4.

**Comment by nielsdrost7** [comment]
@juansecaro thank you for the bug report.
Unfortunately I cannot reproduce the problem.

Since the Steps to reproduce are missing, I had to guess the steps to reproduce:
- Add client
- Fill complete client form
- Add a note
- Go back to the
 Index page
- Click on "Delete client" (see screenshot)
![Screenshot_20240401_060837](https://github.com/InvoicePlane/InvoicePlane/assets/47660417/c35f95b8-8536-47a0-ab7e-57175526da05)
The Client was succesfully deleted, without issues or errors.

InvoicePlane has a forum on https://community.invoiceplane.com
Place your problem there and we'll try to help you with that problem.

Could you fill the complete bug report next time? That would help.
