### ISSUE TITLE
Possibility to backdate a new/draft invoice

### ISSUE THREAD

**Issue by xeroc** [InvoicePlane/InvoicePlane#1043]
When i have a draft invoice with an invoice date X and send out an email tot he client, the invoice is changed to invoice date Y (Y being today).

## Expected Behavior

When i set an invoice date, it should not be modified when sending the invoice out per email

## Current Behavior

1. I set an invoice date at X != today
2. I send out the invoice
3. Invoice date now is today != X

## Flow

I create invoices on one date and have them confirmed by staff. However, I want invoices to be dated at the last day of the month, even if I only manage to send them out 2 days later.

**Comment by nielsdrost7** [comment]
Great issue, man! I'll take a look this weekend. It might be possible, that I merged a PR about this couple of weeks ago.
@mheiduk do you recognize this issue with the fox that you created for it? It might be that your solution is also the solution for this issue? What do you think?

**Comment by nielsdrost7** [comment]
@xeroc looks like you have to do almost the same as this PR: https://github.com/InvoicePlane/InvoicePlane/pull/1040/files
In that PR the due date is't changed due to a setting.

I can also remember an invoice setting that triggered your behaviour, now that I think of it.
Can you go to settings/invoices
There's a setting that doesn't set the invoice date to "today", as far as I know

**Comment by mheiduk** [comment]
@nielsdrost7 Yes, seems to be the same problem which I already fixed in the PR.
@xeroc With the next version this should be fixed. In the meantime, go to System Settings -> Invoices -> Other settings and set `Disable the change of invoice date and due date before emailing` to `Yes`. This should fix your problem.

**Comment by xeroc** [comment]
great. thank you
