### ISSUE TITLE
when i am entering into my website vcelluloid.com it is opening invoiceplane site why can i know

### ISSUE THREAD

**Issue by Kashyap-B** [InvoicePlane/InvoicePlane#1065]
## Steps to Reproduce

1.
2.
3.
4.

**Comment by nielsdrost7** [comment]
@Kashyap-B someone installed InvoicePlane.

So check with your DNS Provider.
Either your website is pointing to another IP address that hosts InvoicePlane.
Or ...
Your own server has InvoicePlane on it.

I would still ask you to ask this on our forums: https://community.invoiceplane.com

But since you're probably not a user of InvoicePlane, I'll leave your question open here for a short while.

**Comment by nielsdrost7** [comment]
Closing this issue. If you have questions open up a question on the forums
