### ISSUE TITLE
No company field in user account screen

### ISSUE THREAD

**Issue by rginus** [InvoicePlane/InvoicePlane#48]
In the table of the user account, there is a field 'user_company', but not in the user account screen.

**Comment by miquel-cabanas** [comment]
I have made a minor change to display the user company in the user account form so that it can be used in the email templates.

In the long term I would propose to use a more standard approach. For instance, assuming we agree on InvoicePlane being a single-company & multiple-users invoicing application (which fits my needs :wink:)

 - the user table/object would only contain information related to the user account: name, password, email, contact data (and in a later version, permissions or roles); and
 - the company table/object would contain all information related to the company: postal address, invoice address;
 - all tables currently linked to the user table through `user_id` would be related to the company table.
