### ISSUE TITLE
[IMPORTANT] Move to Laravel or another framework?

### ISSUE THREAD

**Issue by Kovah** [InvoicePlane/InvoicePlane#68]
Hi devs,
as you may know Invoiceplane is built with _Codeigniter_. Some time ago Ellislabs, the owner of the framework, announced that they are searching for a new owner because they are not longer interested in developing Codeigniter.
Maybe you also know that Codeigniter is great for applications that should support older environments but it's not prepared for the future and a complete rewrite would be needed to support newer PHP versions. I actually don't think that the new owner will rebuild CodeIgniter so I thought about moving Invoiceplane (maybe v2.0) to Laravel. I already worked with Laravel and moving doesn't seems to be a big problem.
But IP is an open source project and the community should decide if we should stay at Codeigniter or move.

Please vote up with `+1` if you agree with Laravel, else leave a comment why not or if you would recommend another framework.
Please leave a comment if you can help developing.

**Comment by MaherSakka** [comment]
+1 Laravel

I used at first MyClientBase then migrated to FusionInvoice, then InvoicePlane.
Last days I decided to find another solutions which is based on a modern framework as Laravel.

I tried NinjaInvoice, it's a good solution which has good features.
Unfortunately, creating a custom invoice template isn't flexible because the template engine is based on JavaScript and not HTML as InvoicePlane.
