### ISSUE TITLE
No direct script access allowed

### ISSUE THREAD

**Issue by franktopel** [InvoicePlane/InvoicePlane#737]
I was trying to follow the installation routine as described.

1. Downloaded the latest version of InvoicePlane.
2. Uploaded all files contained to my hosted webserver.
3. Renamed `ipconfig.php.example` to `ipconfig.php`.
4. Went to the URL and asked for `http://billing.my-domain.com/ipconfig.php`.

All I get is

**No direct script access allowed**

Any suggestions?

Here what the response header says:

```
Overview
URL: http://billing.my-domain.com/ipconfig.php
Status: 200 OK
Source: Network
Adress: **.**.**.**:80

Request
GET /ipconfig.php HTTP/1.1
Cookie: ip_csrf_cookie=2c2e502318666ec7b330aef8a4e85048; ip_session=me3ha1rukhr857669bd8snae7ddlvepi
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Upgrade-Insecure-Requests: 1
Host: billing.my-domain.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15
Accept-Language: de-de
Accept-Encoding: gzip, deflate
Connection: keep-alive

Response
HTTP/1.1 200 OK
Content-Type: text/html; charset=UTF-8
Connection: Keep-Alive
Date: Sun, 13 Jun 2021 10:44:26 GMT
Keep-Alive: timeout=3, max=100
Transfer-Encoding: Identity
Server: Apache/2.4.46 (Unix)
X-Powered-By: PHP/8.0.6
```

**Comment by zeitschlag** [comment]
Hi @franktopel,

thanks for reaching out. In order to install InvoicePlane, you have to visit `http://your-invoiceplane-domain.com/index.php/setup`.
It seems to me, that you're also using a subdomain, so don't forget to configure it in your `ipconfig.php`. You can do so by setting the `IP_URL`: https://github.com/InvoicePlane/InvoicePlane/blob/master/ipconfig.php.example#L8

Let me know if this was helpful :slightly_smiling_face:

**Comment by franktopel** [comment]
Misread your installation instructions. When it said 

4. Open the `ipconfig.php`

that is where I stopped reading and tried to open the file from the URL.

Thanks for your quick help.
