### ISSUE TITLE
Copy Quote UI feedback

### ISSUE THREAD

**Issue by Oxymoron290** [InvoicePlane/InvoicePlane#841]
When creating a copy of a quote (not "copy to invoice"), the user is prompted for various information "Client", "Quote Date", and "Group". When the user selects "Submit" the system properly creates a copy of the quote, however the UI does not change and continues to display the modal asking for "Client", "Quote Date" and "Group" with no feedback that the operation was successful.

**Comment by Verony-makesIT** [comment]
@nielsdrost7: I think there is a misunderstanding and/or some confusion here. This is not a request for an enhancement or improvement but **a bug**. 
@Oxymoron290 please correct me if I am wrong.

Coincidentally, I also encountered this issue a moment ago. 
Several tickets have already been created on the community forum for this as well (e.g. "Quote copy doesn't work - Mar 2021") but to date this has still not been resolved. 

There is an error in the code which causes the wrong data/ids to be passed on. 
Every time the Submit button is clicked a Quote will be created in the background with the same date as the original quote. However, the modal window remains on the page as if nothing happened. You can close this window by clicking (Cancel or close). 
I think the normal procedure should be that when you click the submit button, you would jump directly to the copied quote with the message in the banner at the top that the copy was successful. 

> I will take a look at this and try to resolve this issue.

**Comment by nielsdrost7** [comment]
I've altered it to a bug. Also, @Verony-makesIT I assigned you

**Comment by Verony-makesIT** [comment]
@Niels, no modal.close() or anything like that (_doesn't exist_) and the ajax form doesn't post because _there is no response from the backend._
The problem comes when fetching the 'custom_fields' data. 
As far as I understand it (_I'm not a developer_), the ( existing?) data is retrieved from the custom_fields db and put into an array. 
If there is no data in the db the array cannot be populated and there is **no "response"**. 
Therefore, in modal_copy_quote, the code
```
if (response.success === 1) {
    window.location = "<?php echo site_url('invoices/view'); ?>/" + response.invoice_id;
}
```
is not executed in order to display the quote view page.
I extracted the snippet (_copied the custom_fields_ code) from **mdl_invoice.php** and modified it in **mdl_quotes.php**. 
> **Issue solved!**

Can you please answer my question, regarding this issue **and the other minor bugs/anomaly, in slack** before I proceed with this?

**Comment by nielsdrost7** [comment]
Great job on solving the issue!

> Can you please answer my question, regarding this issue and the other minor bugs/anomaly, in slack before I proceed with this?

Yes, but we'll have to think about it. For now it's great to have at least a solution

**Comment by kelvin-codes-stuff** [comment]
Solved
