### ISSUE TITLE
[Feature Request] Dark Theme

### ISSUE THREAD

**Issue by Oxymoron290** [InvoicePlane/InvoicePlane#843]
my retinas are burning

**Comment by nielsdrost7** [comment]
@Oxymoron290 
It's the Nord color palette: https://lospec.com/palette-list/nord-theme
![image](https://github.com/InvoicePlane/InvoicePlane/assets/47660417/9f3dbcbf-7456-474f-baf1-ec20a4a3fb9a)

Not there yet, but getting there ...

**Comment by nielsdrost7** [comment]
@Oxymoron290 (and everyone else)
Here are some more screenshots.
https://github.com/InvoicePlane/InvoicePlane-Themes/issues/2
It turns out, that InvoicePlane has a dedicated 'themes' repository. I'll update that one with this theme

Just start shooting at it. Preview (also look at that other issue for more screenshots):

### dashboard
![dashboard-1](https://github.com/InvoicePlane/InvoicePlane-Themes/assets/47660417/589b0237-f1f9-4abc-95d3-849d752a9324)

### clients index
![clients-index](https://github.com/InvoicePlane/InvoicePlane-Themes/assets/47660417/bf35bfd3-
b91a-4908-bea5-5713659acaa1)

### client show
![client-show](https://github.com/InvoicePlane/InvoicePlane-Themes/assets/47660417/f3c92e40-eff2-4768-86f4-1d5f95c88ec9)

### invoices index
![invoices-index](https://github.com/InvoicePlane/InvoicePlane-Themes/assets/47660417/7a9a9ffe-399c-41d9-ab3e-b9a1b7914743)

### invoice create modal
![invoice-create-modal](https://github.com/InvoicePlane/InvoicePlane-Themes/assets/47660417/b2506377-04d1-4519-bb96-6edf78c0eb1b)

### invoice created
![invoice-created](https://github.com/InvoicePlane/InvoicePlane-Themes/assets/47660417/a2568487-c2af-426e-995a-31cb15ad184b)

### quotes index
![quotes-index](https://github.com/InvoicePlane/InvoicePlane-Themes/assets/47660417/750846b4-0455-4203-9b92-a8a8cfca31f3)

**Comment by nielsdrost7** [comment]
@Oxymoron290 Verony made an extra dark theme. Check it out here: https://github.com/InvoicePlane/InvoicePlane-Themes/issues/2#issuecomment-1813209227

**Comment by nielsdrost7** [comment]
Version 1.6.1 ([the .zip file with everything in it](https://github.com/InvoicePlane/InvoicePlane/releases/download/v1.6.1/v1.6.1.zip)) has 2 dark themes:
- [und_ip_nord](https://github.com/InvoicePlane/InvoicePlane-Themes/tree/development/v1/und_ip_nord) IP Nord theme, the Nord color template
- [next_ip_dark](https://github.com/InvoicePlane/InvoicePlane-Themes/tree/development/v1/next_ip_dark) A Dark theme by VeronyMakesIT.
They're ready to select in the admin panel.

**Comment by naui95** [comment]
fixed with v1.6.1 see https://github.com/InvoicePlane/InvoicePlane/issues/843#issuecomment-1868491275
