### ISSUE TITLE
Feature Request - Externally Hosted Logo

### ISSUE THREAD

**Issue by moontommy** [InvoicePlane/InvoicePlane#844]
Please add an option to allow the company logo to be hosted externally and provide url instead of uploading it manually.
Also, please allow WebP when uploading the logo manually.
Thanks.

**Comment by nielsdrost7** [comment]
Can you show a screenshot of where you're uploading your logo?

**Comment by moontommy** [comment]
The logo upload is available under "Settings" and then "general" and invoices".
Maybe we could have two radio buttons where option 1 is uploading image like it is now and option 2 is a textbox with option to add url and a submit button.
Screenshots:
Menu interface:
<img width="1653" alt="Screenshot 2022-09-04 at 16 52 53" src="https://user-images.githubusercontent.com/36272482/188319858-8e3a531c-3f29-407b-888f-b236ed28f0ed.png">
General:
<img width="1119" alt="Screenshot 2022-09-04 at 16 53 44" src="https://user-images.githubusercontent.com/36272482/188319853-5da47392-fd52-4500-8d5e-a262c8c855e5.png">
The "login logo" option then allows you to upload a logo that will be shown at login. A similar option under "invoices" lets you upload a logo that will be printed on the invoices.

**Comment by nielsdrost7** [comment]
Great job on the screenshot.

**Comment by moontommy** [comment]
Great job on the sarcasm.

**Comment by nielsdrost7** [comment]
It wasn't sarcasm.
So... show your pull-request and let's see if we cab merge it.
You do know what a pull-request is, right?

**Comment by moontommy** [comment]
Maybe at least drop the sarcasm in comments where you're denying to be sarcastic?
I know what a pull request is, do you know what a feature request is?

**Comment by nielsdrost7** [comment]
I know what a feature request is.
This is not a forum.

I know how to close a feature request as well.

Next time: accompany your feature request with a pull-request.

Your request is closed, because it gives too much trouble for something simple.
Your radio button requires a migration.
A migration gives trouble.

Having a url on a remote location for your invoice logo gives trouble. You'll have to get that logo to generate the invoice which costs time
