### ISSUE TITLE
[MySQL Incorrect DATE value: '0000-00-00'] Running InvoicePlan on WPLocal - Error

### ISSUE THREAD

**Issue by its-me-dennis** [InvoicePlane/InvoicePlane#878]
Hi, i have a special problem, i use WPLocal (https://localwp.com) to create wordpress sites, and i tryed to run invoice plane with it :), the installations seems to run but on my first login i get this error, maybe someone has an idea to help - i am not a programmer but i can edit the files if i know what to search for...

A Database Error Occurred
Error Number: 1525

Incorrect DATE value: '0000-00-00'

SELECT SQL_CALC_FOUND_ROWS ip_quotes.*, ip_users.*, ip_clients.*, ip_invoice_sumex.*, ip_invoice_amounts.invoice_amount_id, IFnull(ip_invoice_amounts.invoice_item_subtotal, '0.00') AS invoice_item_subtotal, IFnull(ip_invoice_amounts.invoice_item_tax_total, '0.00') AS invoice_item_tax_total, IFnull(ip_invoice_amounts.invoice_tax_total, '0.00') AS invoice_tax_total, IFnull(ip_invoice_amounts.invoice_total, '0.00') AS invoice_total, IFnull(ip_invoice_amounts.invoice_paid, '0.00') AS invoice_paid, IFnull(ip_invoice_amounts.invoice_balance, '0.00') AS invoice_balance, ip_invoice_amounts.invoice_sign AS invoice_sign, (CASE WHEN ip_invoices.invoice_status_id NOT IN (1, 4) AND DATEDIFF(NOW(), invoice_date_due) > 0 THEN 1 ELSE 0 END) is_overdue, DATEDIFF(NOW(), invoice_date_due) AS days_overdue, (CASE (SELECT COUNT(*) FROM ip_invoices_recurring WHERE ip_invoices_recurring.invoice_id = ip_invoices.invoice_id and ip_invoices_recurring.recur_next_date <> '0000-00-00') WHEN 0 THEN 0 ELSE 1 END) AS invoice_is_recurring, ip_invoices.* FROM `ip_invoices` JOIN `ip_clients` ON `ip_clients`.`client_id` = `ip_invoices`.`client_id` JOIN `ip_users` ON `ip_users`.`user_id` = `ip_invoices`.`user_id` LEFT JOIN `ip_invoice_amounts` ON `ip_invoice_amounts`.`invoice_id` = `ip_invoices`.`invoice_id` LEFT JOIN `ip_invoice_sumex` ON `sumex_invoice` = `ip_invoices`.`invoice_id` LEFT JOIN `ip_quotes` ON `ip_quotes`.`invoice_id` = `ip_invoices`.`invoice_id` ORDER BY `ip_invoices`.`invoice_id` DESC LIMIT 10

Filename: core/MY_Model.php

Line Number: 157

**Comment by clochenberg09** [comment]
Lets start at the beginning...

First of all what version of IP are you installing?
Secondly what version of PHP are you installing on?

**Comment by clochenberg09** [comment]
I would also recommend rather to use XAMPP (if you are using a windows machine) to use as your webserver when running IP on a local machine. You will get much easier support from the forum that way.

**Comment by naui95** [comment]
Hi @its-me-dennis, this is a known issue caused by the default settings of MySQL which starting from version 5.7 has activated by default the `strict SQL Mode` that does not allow '0000-00-00' dates.
> If strict mode is enabled, '0000-00-00' is not permitted and inserts produce an error
(https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sql-mode-strict)

I think since IPv1 is getting updated in order to support PHP8.1 it might be worth to address also this incompatibility with the newest MySQL default settings.

As a temporary fix setting the SQL mode to `ALLOW_INVALID_DATES` (https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sql-mode-full) should do the trick.

**Comment by nielsdrost7** [comment]
The forums are located at https://community.invoiceplane.com
This question would have been better in its place there, since this is not a bug nor a feature request.

The most important question here is the **MySQL version**.

If it's version **5.7** then apply the excellent advice from naui95.
If the MySQL version of localwp is version **8**, then you're out of luck.
(I couldn't find which MySQL version they are using, by the way)

This is the reason why switching to MariaDB is a better option.
Running Wamp / Xamp will help you with that 

You also have the option to run Docker, even with version 1.5.11 a simple `docker-compose up -d` (after having docker installed) will do the trick and yes, that docket is using MariaDB.

**Comment by its-me-dennis** [comment]
Hi, the mysql version is 8.0.16 but was only a try to run on local :), i set up invoiceplane on my webserver now and is runing. thanks for the help, greetings

**Comment by nielsdrost7** [comment]
@its-me-dennis thanks for the extra info. If you want to try local, try something that's called Docker.

Docker is a thing where you combine your webserver, PHP, MariaDB, but then locally.
Similar to `localwp`, but with Docker you can control the versions of those components
