### ISSUE TITLE
Message: mysqli::real_connect(): Headers and client library minor version mismatch. Headers:100337 Library:100427

### ISSUE THREAD

**Issue by vespino** [InvoicePlane/InvoicePlane#910]
My hoster screwed up by updating MySQL and now I'm faced with the following warning which prevents me from working with InvoicePlane: Message: mysqli::real_connect(): Headers and client library minor version mismatch. Headers:100337 Library:100427

Is there a way to bypass this temporarily?

**Comment by naui95** [comment]
Hi @vespino thank you for reaching out. We might need some more information to help you out on this, like: (i) the current PHP version and (ii) the MySQL version of the database server. Until this is not an InvoicePlane bug/improvement/other it would be best to handle the matter on https://community.invoiceplane.com/. I therefore kindly ask you to open a topic in the community and (for the moment) I will close this issue since it seems to be more hosting related than IP-related.
