### ISSUE TITLE
During installation a user (sometimes) isn't created

### ISSUE THREAD

**Issue by nielsdrost7** [InvoicePlane/InvoicePlane#968]
Investigate

**Comment by colbeagle** [comment]
Hi,

I have this issue 5 min ago and maybe it's linked about it.
Sometime, when I wanted to install InvoicePlane, I had some loops with the installation and impossible to create a user, so the installation end normally without creating the admin user.

I solve this issue by removing CloudFlare Flex SSL by another SSL like let's encrypt.
This issue is very common with CloudFlare on another CMS like Wordpress who do some error with loop.
Hope it help.

**Comment by nielsdrost7** [comment]
Thank you so much for this information man! It helps for sure

**Comment by nielsdrost7** [comment]
> so the installation end normally without creating the admin user

@colbeagle I've added a fix for this issue. Problem is that all we can do is log it when things go wrong.
I've added a check whether there are 0 users after the 'create_user' step. It will then redirect back to that same 'create_user' step (and a log entry will be added)
